
services:
  - type: web
    name: wedding
    runtime: node
    plan: free
    rootDir: backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0

